language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover

after_success:
  - codecov
  - coveralls
